@startuml lifecycle
skinparam Style strictuml
!define LIGHTBLUE
!$FONTNAME = "Ubuntu Mono"
' !$FONTSIZE = 13
skinparam ArrowMessageAlignment center
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

autonumber
skinparam ParticipantPadding 20
skinparam BoxPadding 20

box "Raiz" #LightGreen
' participant Raiz as r
participant Fonte as s
participant "Detector Novidades" as d
end box
box "Folha" #LightBlue
collections Classificador as c
participant "Atualiza Modelo" as m
' participant Leaf as l
end box

' == Initialization ==
' activate r
' activate l
' r -> d ** : <<create>>
' r -> s ** :call

' l -> c ** : <<create>>
' l -> m ** :call

activate s
s --> m ++ : Modelo Inicial
s -> d : Modelo Inicial
' group shared Memory
c <- m : Modelo Compartilhado
deactivate m
' end

' == Running ==
' loop input samples
skinparam SequenceGroupBodyBackgroundColor #LightGreen
group Fluxo Contínuo
activate s
note over s : entrada
s --> c ++ : Exemplo
end
deactivate s

' c -> c ++ :NearestCluster()
' deactivate c

c --> d ++ : Exemplo Rotulado
deactivate c
note over d:saída
d -> d : DetecçãoNovidade()
activate d
deactivate d
d --> m : Atualizaçao Modelo
' activate m
' ... time ...
' |||
deactivate d
' deactivate m


@enduml